1. Task 1: Creating a 1D NumPy Array
Create a NumPy array containing the numbers from 1 to 30.
Print the array and its shape.
Access and print the element at index 10.

In [14]:
import numpy as np

arr = np.arange(1,31)

print(arr)
print(arr.shape)
print(arr[10])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
(30,)
11


2. Task 2: Creating a 2D NumPy Array
Reshape the 1D array from Task 1 into a 2D array of shape (6, 5).
Print the entire 2D array.
Access and print the element at row 3, column 4.

In [15]:
import numpy as np

arr = np.arange(1,31)

arr_2d = arr.reshape(6, 5)

print(arr_2d)
print(arr_2d[3][4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
20


3. Task 3: Subsetting a 2D Array
Extract and print the third row from the 2D array created in Task 2.
Extract and print the first two rows and the last three columns.

In [16]:
print(arr_2d[2])
print(arr_2d[:2, -3:])

[11 12 13 14 15]
[[ 3  4  5]
 [ 8  9 10]]


4. Task 4: Generating Random Integer Array
Use the numpy.random module to generate a 1D array of 15 random integers
between 10 and 100.
Print the array and find its maximum and minimum values.

In [17]:
arr_random = np.random.randint(10,101,15)

print(arr_random)
print(arr_random.max())
print(arr_random.min())

[100  80  96  50  23  49  44  54  60  73  22  51  32  50  48]
100
22


5. Task 5: Generating a 2D Random Array

Lab: Exploring NumPy Arrays and Random Value Generation 2

Generate a 2D array of shape (4, 4) with random integers between 0 and
50.
Print the array and find the sum of all the elements in the array.

In [18]:
arr_random = np.random.randint(0,51,(4,4))
sum = np.sum(arr_random)

print(arr_random)
print(sum)


[[21 12 42 42]
 [25 38  4 30]
 [25 20 26 11]
 [ 3 36 41 47]]
423


6. Task 6: Manipulating Arrays
Create a 2D array of random integers (shape 5, 5) between 1 and 20.
Print the array.
Set all values in the second row to 0.
Replace all values greater than 10 with the value 99.

In [19]:
arr_random = np.random.randint(1,21,(5,5))
print(arr_random)

arr_random[1] = 0
print(arr_random)

arr_random[arr_random > 10] = 99
print(arr_random)

[[ 4  4  9 17 18]
 [12  8 16  4  9]
 [ 1  4 16  3 12]
 [ 3 16 10 19  1]
 [ 1  8 11  8 19]]
[[ 4  4  9 17 18]
 [ 0  0  0  0  0]
 [ 1  4 16  3 12]
 [ 3 16 10 19  1]
 [ 1  8 11  8 19]]
[[ 4  4  9 99 99]
 [ 0  0  0  0  0]
 [ 1  4 99  3 99]
 [ 3 99 10 99  1]
 [ 1  8 99  8 99]]


7. Task 7: Arithmetic Operations on Arrays
Create two 1D arrays of length 5 with random integers between 1 and 10.
Perform element-wise addition, subtraction, and multiplication on the two
arrays.
Print the results.

In [20]:
arr_1 = np.random.randint(1,11,5)
arr_2 = np.random.randint(1,11,5)
print(arr_1)
print(arr_2)

add = arr_1 + arr_2
print(f'addtion: {add}')

sub = arr_1 - arr_2
print(f'substract: {sub}')

multi = arr_1 * arr_2
print(f'multiplication: {multi}')

[9 5 4 8 5]
[ 8 10  6  7  8]
addtion: [17 15 10 15 13]
substract: [ 1 -5 -2  1 -3]
multiplication: [72 50 24 56 40]


8. Task 8: Broadcasting in NumPy
Create a 1D array of length 4 with values [2, 4, 6, 8].
Create a 2D array of shape (3, 4) with random integers between 1 and 5.
Add the 1D array to each row of the 2D array using broadcasting, then
print the result.

In [21]:
arr_1d = np.arange(2,9,2)
print(arr_1d)

arr_2d = np.random.randint(1,6,(3,4))
print(arr_2d)

add = arr_2d + arr_1d
print(add)

[2 4 6 8]
[[2 4 1 2]
 [2 4 2 1]
 [2 4 1 4]]
[[ 4  8  7 10]
 [ 4  8  8  9]
 [ 4  8  7 12]]


9. Task 9: Filtering an Array
Generate a 1D array of 20 random integers between 1 and 100.
Print all elements of the array that are greater than 50.
Replace all values less than 30 with -1 and print the modified array.

In [22]:
arr_1d = np.random.randint(1,101,20)
arr_than_50 = arr_1d[arr_1d > 50]
print(f'origin: {arr_1d}')
print(f'than 50: {arr_than_50}')

arr_1d[arr_1d < 30] = -1
print(f'replace less than 30: {arr_1d}')


origin: [11 78 77 21  2 42  5 18 96 37 41  1 30  5 63 36 91 71 13 48]
than 50: [78 77 96 63 91 71]
replace less than 30: [-1 78 77 -1 -1 42 -1 -1 96 37 41 -1 30 -1 63 36 91 71 -1 48]


10. Task 10: Reshaping Arrays
Create a 1D array of 12 random integers between 1 and 50.
Reshape the array into a 3x4 2D array.
Transpose the array (swap rows and columns) and print the result.

In [23]:
arr_1d = np.random.randint(1,51,12)
arr_2d = arr_1d.reshape(3,4)

print(arr_2d)

arr_trans = arr_2d.transpose()
print(arr_trans)

[[ 9 24 38 45]
 [12 15 15  1]
 [17 17 21 31]]
[[ 9 12 17]
 [24 15 17]
 [38 15 21]
 [45  1 31]]
